/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemahotel.view;

import java.math.BigDecimal;
import javax.swing.JOptionPane;
import sistemahotel.controller.FinanceiroController;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import sistemahotel.model.Funcionario;

/**
 *
 * @author Ray Carvalho
 */
public class FinanceiroViewGUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FinanceiroViewGUI.class.getName());
    private FinanceiroController financeiroController;
    private Funcionario usuarioLogado;
    private MenuViewGUI menuPai;

    /**
     * Creates new form FinanceiroViewGUI
     */
    public FinanceiroViewGUI(MenuViewGUI menuPai, Funcionario usuarioLogado) {
        initComponents();
        this.setLocationRelativeTo(menuPai); // Centraliza a tela em relação ao menu

        this.financeiroController = new FinanceiroController();
        this.usuarioLogado = usuarioLogado; // Guarda o usuário logado
        this.menuPai = menuPai; // Guarda a referência da tela de menu
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        TxtIDReserva = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxtValor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtData = new javax.swing.JTextField();
        CBXTipo = new javax.swing.JComboBox<>();
        BTNRegistrarPagamento = new javax.swing.JButton();
        BTNSaldoDoDia = new javax.swing.JButton();
        BTNEmitirRecibo = new javax.swing.JButton();
        BTNLimpar = new javax.swing.JButton();
        BTNExPDF = new javax.swing.JButton();
        BTNExCVS = new javax.swing.JButton();
        BTNVoltar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("FINANCEIRO - HOTEL");

        jTable1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Reserva", "Valor", "Tipo", "Data", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("ID Reserva:");

        jLabel3.setText("Valor:");

        jLabel4.setText("Tipo:");

        jLabel5.setText("Data:");

        CBXTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pagamento", "Recibimento" }));

        BTNRegistrarPagamento.setText("Registrar Pagamento");
        BTNRegistrarPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNRegistrarPagamentoActionPerformed(evt);
            }
        });

        BTNSaldoDoDia.setText("Ver Saldo Do DIa");
        BTNSaldoDoDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSaldoDoDiaActionPerformed(evt);
            }
        });

        BTNEmitirRecibo.setText("Emitir Recibo");
        BTNEmitirRecibo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEmitirReciboActionPerformed(evt);
            }
        });

        BTNLimpar.setText("Limpar");

        BTNExPDF.setText("Exportar PDF");

        BTNExCVS.setText("Exportar CVS");
        BTNExCVS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNExCVSActionPerformed(evt);
            }
        });

        BTNVoltar.setText("Voltar ao Menu");
        BTNVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNVoltarActionPerformed(evt);
            }
        });

        jLabel6.setText("TABELA DE TRANSAÇÕES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(245, 245, 245)
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TxtIDReserva)
                                    .addComponent(TxtValor, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(TxtData, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(BTNSaldoDoDia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(CBXTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(BTNRegistrarPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BTNLimpar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BTNEmitirRecibo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 6, Short.MAX_VALUE)
                                .addComponent(BTNExPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92)
                                .addComponent(BTNExCVS, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(105, 105, 105)
                                .addComponent(BTNVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator2))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtIDReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(CBXTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNRegistrarPagamento)
                    .addComponent(BTNEmitirRecibo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(TxtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNSaldoDoDia)
                    .addComponent(BTNLimpar))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNExPDF)
                    .addComponent(BTNExCVS)
                    .addComponent(BTNVoltar))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BTNRegistrarPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNRegistrarPagamentoActionPerformed
        try {
            //Ler os dados da tela, incluindo a data
            int idReserva = Integer.parseInt(TxtIDReserva.getText());
            BigDecimal valor = new BigDecimal(TxtValor.getText());
            String tipo = (String) CBXTipo.getSelectedItem();
            String dataTexto = TxtData.getText();

            //Converte o texto da data para o objeto LocalDate que o Controller espera
            java.time.format.DateTimeFormatter formatter = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy");
            java.time.LocalDate data = java.time.LocalDate.parse(dataTexto, formatter);

            //Chamada nova agra com a data
            boolean sucesso = financeiroController.registrarPagamento(idReserva, valor, tipo, data);

            if (sucesso) {
                JOptionPane.showMessageDialog(this, "Pagamento registrado com sucesso!");
            } else {
                JOptionPane.showMessageDialog(this, "Falha ao registrar o pagamento.");
            }
        } catch (java.time.format.DateTimeParseException e) {
            JOptionPane.showMessageDialog(this, "Formato de data inválido. Use dd/MM/yyyy.");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, insira valores numéricos válidos para ID e Valor.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocorreu um erro: " + e.getMessage());
        }
    }//GEN-LAST:event_BTNRegistrarPagamentoActionPerformed

    private void BTNSaldoDoDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSaldoDoDiaActionPerformed
        try {
            String dataTexto = TxtData.getText();
            if (dataTexto.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Por favor, digite uma data no formato dd/MM/yyyy.", "Atenção", JOptionPane.WARNING_MESSAGE);
                return;
            }

            //Converter a data para o formato que o Controller espera
            java.time.format.DateTimeFormatter formatter = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy");
            java.time.LocalDate data = java.time.LocalDate.parse(dataTexto, formatter);

            BigDecimal saldo = financeiroController.calcularSaldoDiario(data);

            JOptionPane.showMessageDialog(this, "O saldo do dia " + dataTexto + " é: R$ " + saldo, "Saldo do Dia", JOptionPane.INFORMATION_MESSAGE);

        } catch (java.time.format.DateTimeParseException e) {
            JOptionPane.showMessageDialog(this, "Formato de data inválido. Use dd/MM/yyyy.", "Erro de Formato", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocorreu um erro ao calcular o saldo: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_BTNSaldoDoDiaActionPerformed

    private void BTNVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNVoltarActionPerformed
        this.dispose();
        this.menuPai.setVisible(true);
    }//GEN-LAST:event_BTNVoltarActionPerformed

    private void BTNEmitirReciboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEmitirReciboActionPerformed

        String idTransacaoStr = JOptionPane.showInputDialog(this, "Digite o ID da Transação para emitir o recibo:");

        if (idTransacaoStr == null || idTransacaoStr.trim().isEmpty()) {
            return; // Usuário cancelou ou não digitou nada
        }

        try {
            int idTransacao = Integer.parseInt(idTransacaoStr);

            //Chama o controller para gerar o texto do recibo
            String recibo = financeiroController.gerarReciboTexto(idTransacao);

            javax.swing.JTextArea textArea = new javax.swing.JTextArea(recibo);
            textArea.setEditable(false);
            javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane(textArea);
            scrollPane.setPreferredSize(new java.awt.Dimension(300, 150));
            JOptionPane.showMessageDialog(this, scrollPane, "Recibo", JOptionPane.INFORMATION_MESSAGE);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, digite um ID válido (número).", "Erro de Formato", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BTNEmitirReciboActionPerformed

    private void BTNExCVSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNExCVSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNExCVSActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNEmitirRecibo;
    private javax.swing.JButton BTNExCVS;
    private javax.swing.JButton BTNExPDF;
    private javax.swing.JButton BTNLimpar;
    private javax.swing.JButton BTNRegistrarPagamento;
    private javax.swing.JButton BTNSaldoDoDia;
    private javax.swing.JButton BTNVoltar;
    private javax.swing.JComboBox<String> CBXTipo;
    private javax.swing.JTextField TxtData;
    private javax.swing.JTextField TxtIDReserva;
    private javax.swing.JTextField TxtValor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
