/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemahotel.view;
import java.util.List;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sistemahotel.controller.FinanceiroController;
import sistemahotel.dao.FuncionarioDAO;
import sistemahotel.model.Funcionario;
import sistemahotel.model.Transacao;
import sistemahotel.view.MenuViewGUI;
/**
 *
 * @author Ray Carvalho
 */
public class FinanceiroViewGUI extends javax.swing.JFrame {
    
   private MenuViewGUI menuPai;
   private FinanceiroController finController;
   private Funcionario usuarioLogado;
   private MenuViewGUI menuViewGUI;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FinanceiroViewGUI.class.getName());
    /**
     * Creates new form FinanceiroViewGUI
     */

    public FinanceiroViewGUI() {
 
    }
    
    public FinanceiroViewGUI(MenuViewGUI menuPai, Funcionario usuarioLogado) {
    initComponents();
    this.menuPai = menuPai;
    this.usuarioLogado = usuarioLogado;
    this.finController = new FinanceiroController();
    atualizarTabela();
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Datainicial = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        CBXTipo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        CBXCategoria = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        DataFinal = new com.toedter.calendar.JDateChooser();
        BTFiltro = new javax.swing.JButton();
        BTLimpar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        BTPagarFuncionario = new javax.swing.JButton();
        BTGerarRelatorio = new javax.swing.JButton();
        BTFecha = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        BTVoltar = new javax.swing.JButton();
        TxtTotalEntrada = new javax.swing.JTextField();
        TxtTotalDeSaida = new javax.swing.JTextField();
        TxtSaldoFinal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setText("FINANCEIRO - HOTEL");

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setText("Data Inicial: ");

        Tabela.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Tipo", "Valor", "Data", "Forma D. Pagamento", "Categoria", "Descrição", "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabela);

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel3.setText("Tipo:");

        CBXTipo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CBXTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS", "ENTRADA", "SAÌDA" }));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Categoria:");

        CBXCategoria.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CBXCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODAS", "RESERVA", "SALÁRIO" }));

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel5.setText("Data FInal:");

        BTFiltro.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        BTFiltro.setText("Filtrar");
        BTFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTFiltroActionPerformed(evt);
            }
        });

        BTLimpar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        BTLimpar.setText("Limpar");
        BTLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTLimparActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel6.setText("TOTAL DE ENTRADA:");

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel7.setText("SALDO FINAL:");

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel8.setText("TOTAL DE SAÍDAS:");

        BTPagarFuncionario.setText("Pagar Funcionario");
        BTPagarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTPagarFuncionarioActionPerformed(evt);
            }
        });

        BTGerarRelatorio.setText("Gerar Relatório");

        BTFecha.setText("Fechar");
        BTFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTFechaActionPerformed(evt);
            }
        });

        BTVoltar.setText("Voltar");
        BTVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTVoltarActionPerformed(evt);
            }
        });

        TxtTotalEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTotalEntradaActionPerformed(evt);
            }
        });

        TxtTotalDeSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTotalDeSaidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(374, 374, 374))
            .addComponent(jSeparator2)
            .addComponent(jSeparator4)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 843, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CBXTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(CBXCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(204, 204, 204)
                        .addComponent(BTFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(BTLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Datainicial, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(132, 132, 132)
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(DataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtTotalEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(12, 12, 12)
                        .addComponent(TxtTotalDeSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtSaldoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BTPagarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BTGerarRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BTVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(Datainicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(BTFiltro)
                                .addComponent(BTLimpar))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(CBXTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(CBXCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(DataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(TxtTotalEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtTotalDeSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtSaldoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTGerarRelatorio)
                    .addComponent(BTFecha)
                    .addComponent(BTPagarFuncionario)
                    .addComponent(BTVoltar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTVoltarActionPerformed
        this.dispose();
        this.menuPai.setVisible(true);
    }//GEN-LAST:event_BTVoltarActionPerformed

    private void TxtTotalEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTotalEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTotalEntradaActionPerformed

    private void TxtTotalDeSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTotalDeSaidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTotalDeSaidaActionPerformed

    private void BTPagarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTPagarFuncionarioActionPerformed
        PagarFuncionarioViewGUI pagarfuncionario = new PagarFuncionarioViewGUI();
        pagarfuncionario.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTPagarFuncionarioActionPerformed

    private void BTFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTFechaActionPerformed
        this.dispose();
    }//GEN-LAST:event_BTFechaActionPerformed

    private void BTFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTFiltroActionPerformed
        try {
        LocalDate dataInicio = Datainicial.getDate() != null 
                ? Datainicial.getDate().toInstant().atZone(ZoneId.systemDefault(
                )).toLocalDate() : null;
        LocalDate dataFim = DataFinal.getDate() != null ? 
                DataFinal.getDate().toInstant().atZone(ZoneId.systemDefault())
                        .toLocalDate() : null;
        String tipo = (String) CBXTipo.getSelectedItem();
        String categoria = (String) CBXCategoria.getSelectedItem();

        List<Transacao> transacoes = finController.buscarTransacoesFiltradas(
                dataInicio, dataFim, tipo, categoria);

        DefaultTableModel model = (DefaultTableModel) Tabela.getModel();
        model.setRowCount(0);

        BigDecimal totalEntrada = BigDecimal.ZERO;
        BigDecimal totalSaida = BigDecimal.ZERO;

        for (Transacao t : transacoes) {
            model.addRow(new Object[]{
                t.getTipo(),
                t.getValor(),
                t.getDataTransacao().format(DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm")),
                t.getFormaPagamento(),
                t.getCategoria(),
                t.getDescricao(),
                t.getNomeRelacionado()
            });

            if ("ENTRADA".equalsIgnoreCase(t.getTipo())) {
                totalEntrada = totalEntrada.add(t.getValor());
            } else if ("SAIDA".equalsIgnoreCase(t.getTipo())) {
                totalSaida = totalSaida.add(t.getValor());
            }
        }

        TxtTotalEntrada.setText(totalEntrada.toString());
        TxtTotalDeSaida.setText(totalSaida.toString());
        TxtSaldoFinal.setText(totalEntrada.subtract(totalSaida).toString());

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao aplicar filtro: " + e.getMessage());
    }

    }//GEN-LAST:event_BTFiltroActionPerformed

    private void BTLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTLimparActionPerformed
        // Limpa os campos de filtro
        Datainicial.setDate(null);
        DataFinal.setDate(null);
        CBXTipo.setSelectedIndex(0);       // Supondo que "Todos" esteja na posição 0
        CBXCategoria.setSelectedIndex(0);  // Supondo que "Todas" esteja na posição 0

        // Recarrega todas as transações
        atualizarTabela();
    }//GEN-LAST:event_BTLimparActionPerformed

    private void atualizarTabela() {
    try {
        List<Transacao> transacoes = finController.buscarTodasTransacoes();

        DefaultTableModel model = (DefaultTableModel) Tabela.getModel();
        model.setRowCount(0); // limpa a tabela

        BigDecimal totalEntrada = BigDecimal.ZERO;
        BigDecimal totalSaida = BigDecimal.ZERO;

        for (Transacao t : transacoes) {
            model.addRow(new Object[]{
                t.getTipo(),
                t.getValor(),
                t.getDataTransacao().format(DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm")),
                t.getFormaPagamento(),
                t.getCategoria(),
                t.getDescricao(),
                t.getNomeRelacionado()
            });

            if ("ENTRADA".equalsIgnoreCase(t.getTipo())) {
                totalEntrada = totalEntrada.add(t.getValor());
            } else if ("SAIDA".equalsIgnoreCase(t.getTipo())) {
                totalSaida = totalSaida.add(t.getValor());
            }
        }

        TxtTotalEntrada.setText(totalEntrada.toString());
        TxtTotalDeSaida.setText(totalSaida.toString());
        TxtSaldoFinal.setText(totalEntrada.subtract(totalSaida).toString());

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao carregar dados: " + e.getMessage());
    }
}

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FinanceiroViewGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTFecha;
    private javax.swing.JButton BTFiltro;
    private javax.swing.JButton BTGerarRelatorio;
    private javax.swing.JButton BTLimpar;
    private javax.swing.JButton BTPagarFuncionario;
    private javax.swing.JButton BTVoltar;
    private javax.swing.JComboBox<String> CBXCategoria;
    private javax.swing.JComboBox<String> CBXTipo;
    private com.toedter.calendar.JDateChooser DataFinal;
    private com.toedter.calendar.JDateChooser Datainicial;
    private javax.swing.JTable Tabela;
    private javax.swing.JTextField TxtSaldoFinal;
    private javax.swing.JTextField TxtTotalDeSaida;
    private javax.swing.JTextField TxtTotalEntrada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}