/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemahotel.view;

import java.math.BigDecimal;
import java.util.List;
import java.util.Optional;
import javax.swing.JOptionPane;
import sistemahotel.controller.PagarFuncionarioController;
import sistemahotel.model.Funcionario;
import sistemahotel.model.PagamentoFuncionario;

/**
 *
 * @author Ray Carvalho
 */
public class PagarFuncionarioViewGUI extends javax.swing.JFrame {
    
    private final PagarFuncionarioController controller = new PagarFuncionarioController();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PagarFuncionarioViewGUI.class.getName());

    /**
     * Creates new form PagarFuncionarioViewGUI
     */
    
    
    public PagarFuncionarioViewGUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        carregarFuncionarios();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        CBNomeFuncionario = new javax.swing.JComboBox<>();
        TxtIDDoFuncionario = new javax.swing.JTextField();
        TXTCargoDoFuncionario = new javax.swing.JTextField();
        TXTValorSerPago = new javax.swing.JTextField();
        DataDoPagamento = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        TXTADescricao = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        SalarioDoFuncionario = new javax.swing.JTextField();
        BTNConfimar = new javax.swing.JButton();
        BTNCancelar = new javax.swing.JButton();
        BTNEditar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        CBXFormaDePagamento = new javax.swing.JComboBox<>();
        BTLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setText("Tela De Pagamento");

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setText("Funcionario:");

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel3.setText("ID Do Funcionario:");

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel4.setText("Cargo:");

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel5.setText("Valor a Ser Pago:");

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel6.setText("Data Do Pagamento:");

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel7.setText("Descrição/Observação:");

        CBNomeFuncionario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o Funcionario" }));
        CBNomeFuncionario.setToolTipText("");
        CBNomeFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBNomeFuncionarioActionPerformed(evt);
            }
        });

        TxtIDDoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtIDDoFuncionarioActionPerformed(evt);
            }
        });

        TXTCargoDoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTCargoDoFuncionarioActionPerformed(evt);
            }
        });

        TXTADescricao.setColumns(20);
        TXTADescricao.setRows(5);
        jScrollPane1.setViewportView(TXTADescricao);

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel8.setText("Salario Do Funcionario:");

        SalarioDoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalarioDoFuncionarioActionPerformed(evt);
            }
        });

        BTNConfimar.setText("Confimar");
        BTNConfimar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNConfimarActionPerformed(evt);
            }
        });

        BTNCancelar.setText("Cancelar");
        BTNCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCancelarActionPerformed(evt);
            }
        });

        BTNEditar.setText("Editar");
        BTNEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEditarActionPerformed(evt);
            }
        });

        jLabel9.setText("Forma:");

        CBXFormaDePagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dinheiro", "Pix", "Boleto", "Transferência" }));

        BTLimpar.setText("Limpar");
        BTLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(CBNomeFuncionario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BTNConfimar, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(BTNCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BTNEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BTLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TXTValorSerPago, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CBXFormaDePagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(17, 17, 17))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(TXTCargoDoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TxtIDDoFuncionario))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(18, 18, 18)
                            .addComponent(SalarioDoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(DataDoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(CBNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(SalarioDoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TxtIDDoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(TXTCargoDoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(TXTValorSerPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(CBXFormaDePagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(DataDoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(BTNConfimar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTNCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTNEditar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //Exibir os nomes dos funcionarios no JCombox
    private void carregarFuncionarios() {
        List<String> nomes = controller.listarNomesFuncionarios();
        for (String nome : nomes) {
        CBNomeFuncionario.addItem(nome);
    }
}
    
    private void CBNomeFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBNomeFuncionarioActionPerformed
        String nomeSelecionado = (String) CBNomeFuncionario.getSelectedItem();

    if (nomeSelecionado != null && !nomeSelecionado.trim().isEmpty()) {
        controller.buscarFuncionario(nomeSelecionado).ifPresent(func -> {
            TxtIDDoFuncionario.setText(String.valueOf(func.getId()));
            SalarioDoFuncionario.setText(func.getSalario().toPlainString());
            TXTCargoDoFuncionario.setText(func.getCargo());
        });
    }

    }//GEN-LAST:event_CBNomeFuncionarioActionPerformed

    private void BTNConfimarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNConfimarActionPerformed
    try {
        PagamentoFuncionario pagamento = new PagamentoFuncionario();
        pagamento.setNome((String) CBNomeFuncionario.getSelectedItem());
        pagamento.setId(Integer.parseInt(TxtIDDoFuncionario.getText()));
        pagamento.setCargo(TXTCargoDoFuncionario.getText());
        pagamento.setSalario(new BigDecimal(SalarioDoFuncionario.getText()));
        pagamento.setValorPago(new BigDecimal(TXTValorSerPago.getText()));
        pagamento.setDataPagamento(DataDoPagamento.getDate());
        pagamento.setFormaDePagamento((String) CBXFormaDePagamento.getSelectedItem());
        pagamento.setDescricao(TXTADescricao.getText());

        controller.registrarPagamento(pagamento);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao registrar pagamento: " + e.getMessage());
        e.printStackTrace();
        }
    }//GEN-LAST:event_BTNConfimarActionPerformed

    private void SalarioDoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalarioDoFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalarioDoFuncionarioActionPerformed

    private void TxtIDDoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIDDoFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtIDDoFuncionarioActionPerformed

    private void TXTCargoDoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTCargoDoFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTCargoDoFuncionarioActionPerformed

    private void BTNEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNEditarActionPerformed

    private void BTLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTLimparActionPerformed
        CBNomeFuncionario.setSelectedIndex(-1); // limpa seleção
        TxtIDDoFuncionario.setText("");
        TXTCargoDoFuncionario.setText("");
        SalarioDoFuncionario.setText("");
        TXTValorSerPago.setText("");
        TXTADescricao.setText("");
        CBXFormaDePagamento.setSelectedIndex(-1); // limpa seleção
        DataDoPagamento.setDate(null);

    }//GEN-LAST:event_BTLimparActionPerformed
    
    private MenuViewGUI menuPai;
    private Funcionario usuarioLogado;

    public PagarFuncionarioViewGUI(MenuViewGUI menuPai, Funcionario usuarioLogado) {
    this.menuPai = menuPai;
    this.usuarioLogado = usuarioLogado;
    initComponents();
    carregarFuncionarios();
}
    
    private void BTNCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCancelarActionPerformed
        FinanceiroViewGUI financeiroViewGUI = new FinanceiroViewGUI(menuPai, usuarioLogado);
        financeiroViewGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTNCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PagarFuncionarioViewGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTLimpar;
    private javax.swing.JButton BTNCancelar;
    private javax.swing.JButton BTNConfimar;
    private javax.swing.JButton BTNEditar;
    private javax.swing.JComboBox<String> CBNomeFuncionario;
    private javax.swing.JComboBox<String> CBXFormaDePagamento;
    private com.toedter.calendar.JDateChooser DataDoPagamento;
    private javax.swing.JTextField SalarioDoFuncionario;
    private javax.swing.JTextArea TXTADescricao;
    private javax.swing.JTextField TXTCargoDoFuncionario;
    private javax.swing.JTextField TXTValorSerPago;
    private javax.swing.JTextField TxtIDDoFuncionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
